apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bw72oyc13-nodejs-gitops
  description: This is GitOps manifest for bw72oyc13-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=bw72oyc13-nodejs
    backstage.io/kubernetes-id: bw72oyc13-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bw72oyc13-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bw72oyc13-nodejs
