apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bw72oyc13-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bw72oyc13-nodejs 
  name: bw72oyc13-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bw72oyc13-nodejs 
